UI ux 7
MarlonDSC/medired pull request #59
Opened 2023-10-06 16:12 UTC by wheliver

requerimientos

2023-10-06 17:07 UTC, MarlonDSC requested changes
![image](https://github.com/MarlonDSC/medired/assets/21266228/a2df1da7-547d-443e-aa14-a7971af47256)
El texto es muy grande y tampoco es legible por el color. Agrega un botón para cerrar

2023-10-07 00:52 UTC, wheliver commented
Listo , por favor revisar

2023-10-07 03:04 UTC, MarlonDSC requested changes
Agrega un botón para cerrar el dialog

2023-10-07 22:23 UTC, wheliver commented
calendar and form

2023-10-08 02:16 UTC, MarlonDSC approved these changes

2023-10-08 02:17 UTC, merged